In [2]:
import torch

# Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number vector, matrix, or n-dimensional array. Let's create a tensor with a single numer.

In [3]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

4. is a shorthand for 4.0. It is used to indicate to Python (and PyTorch) that you want to create a floating-point number. We can verify this by checking the dtype attribute of our tensor.

In [4]:
t1.dtype

torch.float32

Let's try creating more complex tensors.

In [5]:
# creating tensor from Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Creating tensor from Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3-d arry as a tensor

# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor.

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

a null element as shape is []

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

Note that it's not possible to create tensors with an improper shape.


In [12]:
# Matrix 
t5 = torch.tensor([[5., 6, 11],
                   [7,8],
                   [9,10]])

t5

ValueError: expected sequence of length 3 at dim 1 (got 2)

A ValueError is thrown because the lengths of the rows [5., 6, 11] and [7, 8] don't match.

Tensor operations and gradients 

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [13]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)

# required_grad helps to calculate the gradient during backpropagagtion

b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: x, w, and b, all numbers. w and b have an additional parameter requires_grad set to True. We'll see what it does in just a moment.

Let's create a new tensor y by combining these tensors.

In [14]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).

To compute the derivatives, we can invoke the .backward method on our result y.

In [15]:
# Compute derivatives 
y.backward()

In [16]:
w.grad

tensor(3.)

In [17]:
b.grad

tensor(1.)

In [18]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

## Tensor functions

Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [19]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [23]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [24]:
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [20]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [21]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [22]:
# Change the shape of a tensor   from 2d tensor to 3d tensor 
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Interoperability with Numpy

Numpy is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

* Pandas for file I/O and data analysis
* Matplotlib for plotting and visualization
* OpenCV for image and video processing


Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:

In [25]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

In [26]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [27]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [28]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

# Linear Regression from scrach using pytorch

In [29]:
import numpy as np
import torch

In [30]:
#making training data 
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [31]:
# Targets (apples, oranges)
target = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [32]:
#Convert input and target to tensors
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

print(inputs,"\n")
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [33]:
# weights and biases
w = torch.randn(2,3 , requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w)
print(b)

tensor([[-1.0344,  0.7317,  0.5768],
        [-0.1247,  1.4045, -0.5144]], requires_grad=True)
tensor([ 0.5147, -0.8908], requires_grad=True)


In [34]:
#define the model

def model(x):
  return x @ w.t() + b

In [35]:
# prediction
preds = model(inputs)
print(preds)

tensor([[ -1.1735,  61.9887],
        [  7.6846,  78.4366],
        [ 42.0190, 146.6284],
        [-52.1923,  27.7503],
        [ 39.7556,  89.3301]], grad_fn=<AddBackward0>)


In [36]:
#actual
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [37]:
# loss function MSE
def MSE(actual, target):
  diff = actual - target
  return torch.sum(diff * diff) / diff.numel()

In [38]:
# error
loss = MSE(target, preds)
print(loss)

tensor(2579.9260, grad_fn=<DivBackward0>)


In [39]:
# compute gradients
loss.backward()

In [40]:
print(w, "\n")
print(w.grad)

tensor([[-1.0344,  0.7317,  0.5768],
        [-0.1247,  1.4045, -0.5144]], requires_grad=True) 

tensor([[-5894.8379, -5971.9126, -3757.5535],
        [ -888.6219,  -788.4337,  -683.4446]])


In [41]:
print(b, "\n")
print(b.grad)

tensor([ 0.5147, -0.8908], requires_grad=True) 

tensor([-68.9813, -11.1732])


In [42]:
#reset grad
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [43]:
# adjust params

preds = model(inputs)
print(preds)

tensor([[ -1.1735,  61.9887],
        [  7.6846,  78.4366],
        [ 42.0190, 146.6284],
        [-52.1923,  27.7503],
        [ 39.7556,  89.3301]], grad_fn=<AddBackward0>)


In [44]:
# loss
loss = MSE(target, preds)
print(loss)

tensor(2579.9260, grad_fn=<DivBackward0>)


In [45]:
loss.backward()

print(w.grad, "\n")
print(b.grad)

tensor([[-5894.8379, -5971.9126, -3757.5535],
        [ -888.6219,  -788.4337,  -683.4446]]) 

tensor([-68.9813, -11.1732])


In [46]:
  # adjust weight & reset grad
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [47]:
print(w)
print(b)

tensor([[-0.9755,  0.7914,  0.6143],
        [-0.1158,  1.4124, -0.5075]], requires_grad=True)
tensor([ 0.5154, -0.8907], requires_grad=True)


In [48]:
# calculate again
preds = model(inputs)
loss = MSE(target, preds)
print(loss)

tensor(1793.0745, grad_fn=<DivBackward0>)


In [49]:
# Training for multiple epochs
for i in range(400):
  preds = model(inputs)
  loss = MSE(target, preds)
  loss.backward()

  with torch.no_grad():
     w -= w.grad * 1e-5 # learning rate
     b -= b.grad * 1e-5
     w.grad.zero_()
     b.grad.zero_()
  print(f"Epochs({i}/{100}) & Loss {loss}")

Epochs(0/100) & Loss 1793.074462890625
Epochs(1/100) & Loss 1262.53564453125
Epochs(2/100) & Loss 904.724609375
Epochs(3/100) & Loss 663.3155517578125
Epochs(4/100) & Loss 500.3505859375
Epochs(5/100) & Loss 390.2509765625
Epochs(6/100) & Loss 315.7796630859375
Epochs(7/100) & Loss 265.3199157714844
Epochs(8/100) & Loss 231.0445098876953
Epochs(9/100) & Loss 207.67788696289062
Epochs(10/100) & Loss 191.66526794433594
Epochs(11/100) & Loss 180.61123657226562
Epochs(12/100) & Loss 172.90097045898438
Epochs(13/100) & Loss 167.44692993164062
Epochs(14/100) & Loss 163.51559448242188
Epochs(15/100) & Loss 160.6131134033203
Epochs(16/100) & Loss 158.4064483642578
Epochs(17/100) & Loss 156.6708984375
Epochs(18/100) & Loss 155.25546264648438
Epochs(19/100) & Loss 154.0581512451172
Epochs(20/100) & Loss 153.01004028320312
Epochs(21/100) & Loss 152.0648956298828
Epochs(22/100) & Loss 151.1914825439453
Epochs(23/100) & Loss 150.36843872070312
Epochs(24/100) & Loss 149.58206176757812
Epochs(25/100)

In [50]:
preds = model(inputs)
loss = MSE(target, preds)
print(loss)

tensor(54.3408, grad_fn=<DivBackward0>)


In [51]:
from math import sqrt
sqrt(loss)

7.3716231551738005

In [52]:
preds

tensor([[ 56.9662,  70.9309],
        [ 82.3482,  93.3911],
        [118.6931, 148.5109],
        [ 19.4476,  40.7168],
        [103.2223, 104.1395]], grad_fn=<AddBackward0>)

In [53]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

## we can see they are almost close each other

# Neural Network using Pytorch