Version check for tensorflow

In [5]:
import tensorflow as tf

print ("Tensorflow version: {}". format(tf.__version__))
print ("Eager execution is: {}". format(tf.executing_eagerly))
print ("Keras version: {}". format(tf.keras.__version__))

Tensorflow version: 2.12.0
Eager execution is: <function executing_eagerly at 0x0000028ABD464EA0>
Keras version: 2.12.0


In [6]:

if tf.config.list_physical_devices('GPU'):
    print("Running on GPU")
else:
    print("Running on CPU")


Running on CPU


Tensor Constant

In [7]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
ineuron.numpy()

42

In [9]:
ineuron1 = tf.constant(1, dtype= tf.int64)
ineuron1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [11]:
# passing 2D array to the constant value
ineuron_x = tf.constant([[4,2], [9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)
