Version check for tensorflow

In [5]:
import tensorflow as tf

# Check TensorFlow version
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly))

# Check Keras version (if using TensorFlow 2.x)
keras_version = tf.keras.__version__ if hasattr(tf.keras, '__version__') else "Not available"
print("Keras version: {}".format(keras_version))


TensorFlow version: 2.15.0
Eager execution is: <function executing_eagerly at 0x0000020AFF78ECA0>
Keras version: Not available


In [6]:

if tf.config.list_physical_devices('GPU'):
    print("Running on GPU")
else:
    print("Running on CPU")


Running on CPU


Tensor Constant

In [7]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
ineuron.numpy()

42

In [9]:
ineuron1 = tf.constant(1, dtype= tf.int64)
ineuron1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [10]:
# passing 2D array to the constant value
ineuron_x = tf.constant([[4,2], [9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [11]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]])

In [12]:
print('shape:', ineuron_x.shape)
print(ineuron_x.dtype)


shape: (2, 2)
<dtype: 'int32'>


Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones and np.zeros

In [13]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [14]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [15]:
# declaring multiple constants
const2 = tf.constant([[3,4,5], [3,4,5]])
const1 = tf.constant([[1,2,3], [1,2,3]])
result = tf.add(const1,const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


Random Constant

In [16]:
# generating shape using standard normal distribution 
tf.random.normal(shape = (2,2), mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.40049267, 0.27113137],
       [1.045643  , 0.49730957]], dtype=float32)>

In [17]:
tf.random.uniform(shape = (2,2), minval= 0, maxval= 10, dtype= tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 9],
       [1, 0]])>

Variables in Tensorflow

In [18]:
# Declaring Variables
var0 = 24   # python variables

var1 = tf.Variable(42)   #rank 0 tensor
var2 = tf.Variable([[[0., 1., 2.], [3., 4., 5.]], [[6., 7., 8.], [9., 10., 11.]]])  #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [19]:
# data type can be explicitly specified 
float_var64 = tf.Variable(89, dtype=tf.float64)
float_var64.dtype

tf.float64

In [20]:
# Reassigning the value 
var_reassign = tf.Variable(89.)  # float value
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [21]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [22]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)



<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.10706266, -1.8513657 ],
       [-0.8086212 , -0.18995406]], dtype=float32)>


We can generally assign '=' with assign (value), or assign_add (value) with "+=", or assign_sub (value) "-="


In [23]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i,j]

In [24]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] + added_value[i,j]

shaping a tensor 

In [26]:
tensor = tf.Variable([[[0., 1., 2.], [3., 4., 5.]], [[6., 7., 8.,], [9., 10., 11.]]]) # tensor variable
print(tensor.shape)

(2, 2, 3)


Tensors may be reshaped and retain the same values, as is often required for constructing neural networks

In [27]:
tensor1 = tf.reshape(tensor, [2,6]) # 2 rows 6 cols
tensor2 = tf.reshape(tensor, [1,12]) # 1 rows 12 cols

tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [28]:
tensor2 = tf.reshape(tensor, [1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

Ranking (dimensions) of a tensor

The rank of a tensor is the number of dimensions it has, that is the number of indices that are required to specify any particular
element of that tensor. 

In [30]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [31]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

the shape is () because the output here is a scalar value 

# Specifying the element of a tensor 

In [34]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

# Casting a tensor to a Numpy/ Python variable

In [35]:
print(tensor.numpy())


[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [36]:
print(tensor[1, 0, 2].numpy())

8.0


# Finding the size(number of elements) of a tensor

In [37]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [38]:
# the datatype of tensor
tensor3.dtype

tf.float32

# Mathematical Operations in Tensorflow

can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU


In [39]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)

print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 0.79370695  0.9062559 ]
 [ 0.02865796 -0.2878695 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.01548235 -0.30698687]
 [-0.3427344  -0.386802  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.7782246   0.59926903]
 [-0.31407645 -0.67467153]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.6056335  0.35912338]
 [0.09864402 0.4551817 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.1776028 1.8207874]
 [0.7304632 0.5093237]], shape=(2, 2), dtype=float32)


Performing element wise primitive tensor operations


In [40]:
tensor * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

In [41]:
tensor + tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  2.,  4.],
        [ 6.,  8., 10.]],

       [[12., 14., 16.],
        [18., 20., 22.]]], dtype=float32)>

In [42]:
tensor - tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

# Broadcasting

Element wise tensor operatios support broadcasting in the same way that NumPy arrays do. The simplest example is that of multiplying a tensor by a scalar:

In [43]:
tensor4 = tensor* 4
print(tensor4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


The scalar multipler 4 is conceptually at least - expanded into an array that can be mulitiplied element wise with t2

Transpose Matrix Multiplication 

In [44]:
matrix_u = tf.constant([[3,4,3]])
matrix_v = tf.constant([[1,2,1]])

tf.matmul(matrix_u, tf.transpose(a= matrix_v))



<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

# Casting a tensor to another (tensor) datatype 
 

In [45]:
i = tf.cast(tensor1, dtype= tf.int32)

i 

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

With truncation 


In [46]:
j = tf.cast(tf.constant(4.9), dtype= tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

# Declaring Ragged Tensors

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths. There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array. 

The following example shows how to declare a constant ragged array and the lengths of the individual slices:

In [47]:
ragged = tf.ragged.constant([[3,2,6,1], [], [4,10,7], [8], [6,7]])

print(ragged)

<tf.RaggedTensor [[3, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>


In [49]:
print(ragged[0])

tf.Tensor([3 2 6 1], shape=(4,), dtype=int32)


In [50]:
print(ragged[1])

tf.Tensor([], shape=(0,), dtype=int32)


In [51]:
print(ragged[2])

tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)


In [52]:
print(ragged[3])

tf.Tensor([8], shape=(1,), dtype=int32)


In [53]:
print(ragged[4])

tf.Tensor([6 7], shape=(2,), dtype=int32)


# Finding the square difference between two tensors


In [54]:
varx = [1,3,5,7,11]
vary = 5
varz = tf.math.squared_difference(varx, vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36])>