Version check for tensorflow

In [2]:
import tensorflow as tf

# Check TensorFlow version
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly))

# Check Keras version (if using TensorFlow 2.x)
keras_version = tf.keras.__version__ if hasattr(tf.keras, '__version__') else "Not available"
print("Keras version: {}".format(keras_version))



TensorFlow version: 2.15.0
Eager execution is: <function executing_eagerly at 0x000002565C4CEA20>
Keras version: Not available


In [3]:

if tf.config.list_physical_devices('GPU'):
    print("Running on GPU")
else:
    print("Running on CPU")


Running on CPU


Tensor Constant

In [4]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
ineuron.numpy()

42

In [6]:
ineuron1 = tf.constant(1, dtype= tf.int64)
ineuron1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [7]:
# passing 2D array to the constant value
ineuron_x = tf.constant([[4,2], [9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [8]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]])

In [9]:
print('shape:', ineuron_x.shape)
print(ineuron_x.dtype)


shape: (2, 2)
<dtype: 'int32'>


Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones and np.zeros

In [10]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [12]:
# declaring multiple constants
const2 = tf.constant([[3,4,5], [3,4,5]])
const1 = tf.constant([[1,2,3], [1,2,3]])
result = tf.add(const1,const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


Random Constant

In [13]:
# generating shape using standard normal distribution 
tf.random.normal(shape = (2,2), mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.7522344 , -0.39879996],
       [ 1.7840427 , -1.2997149 ]], dtype=float32)>

In [14]:
tf.random.uniform(shape = (2,2), minval= 0, maxval= 10, dtype= tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 8],
       [4, 4]])>

Variables in Tensorflow

In [15]:
# Declaring Variables
var0 = 24   # python variables

var1 = tf.Variable(42)   #rank 0 tensor
var2 = tf.Variable([[[0., 1., 2.], [3., 4., 5.]], [[6., 7., 8.], [9., 10., 11.]]])  #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [16]:
# data type can be explicitly specified 
float_var64 = tf.Variable(89, dtype=tf.float64)
float_var64.dtype

tf.float64

In [17]:
# Reassigning the value 
var_reassign = tf.Variable(89.)  # float value
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [18]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [19]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)



<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.09106576,  0.3820568 ],
       [-0.02280557,  0.6961661 ]], dtype=float32)>


We can generally assign '=' with assign (value), or assign_add (value) with "+=", or assign_sub (value) "-="


In [20]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i,j]

In [21]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] + added_value[i,j]

shaping a tensor 

In [22]:
tensor = tf.Variable([[[0., 1., 2.], [3., 4., 5.]], [[6., 7., 8.,], [9., 10., 11.]]]) # tensor variable
print(tensor.shape)

(2, 2, 3)


Tensors may be reshaped and retain the same values, as is often required for constructing neural networks

In [23]:
tensor1 = tf.reshape(tensor, [2,6]) # 2 rows 6 cols
tensor2 = tf.reshape(tensor, [1,12]) # 1 rows 12 cols

tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [24]:
tensor2 = tf.reshape(tensor, [1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

Ranking (dimensions) of a tensor

The rank of a tensor is the number of dimensions it has, that is the number of indices that are required to specify any particular
element of that tensor. 

In [25]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [26]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

the shape is () because the output here is a scalar value 

# Specifying the element of a tensor 

In [27]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

# Casting a tensor to a Numpy/ Python variable

In [28]:
print(tensor.numpy())


[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [29]:
print(tensor[1, 0, 2].numpy())

8.0


# Finding the size(number of elements) of a tensor

In [30]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [31]:
# the datatype of tensor
tensor3.dtype

tf.float32

# Mathematical Operations in Tensorflow

can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU


In [32]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)

print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-1.6940286   0.2625312 ]
 [-0.32890204  0.50476956]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.76465577  0.03724288]
 [ 0.126595    1.4902179 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.4586844   0.29977408]
 [-0.20230703  1.9949875 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[6.0451293  0.0898645 ]
 [0.04092813 3.979975  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.08554742 1.3495538 ]
 [0.8168441  7.352111  ]], shape=(2, 2), dtype=float32)


Performing element wise primitive tensor operations


In [33]:
tensor * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

In [34]:
tensor + tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  2.,  4.],
        [ 6.,  8., 10.]],

       [[12., 14., 16.],
        [18., 20., 22.]]], dtype=float32)>

In [35]:
tensor - tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

# Broadcasting

Element wise tensor operatios support broadcasting in the same way that NumPy arrays do. The simplest example is that of multiplying a tensor by a scalar:

In [36]:
tensor4 = tensor* 4
print(tensor4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


The scalar multipler 4 is conceptually at least - expanded into an array that can be mulitiplied element wise with t2

Transpose Matrix Multiplication 

In [37]:
matrix_u = tf.constant([[3,4,3]])
matrix_v = tf.constant([[1,2,1]])

tf.matmul(matrix_u, tf.transpose(a= matrix_v))



<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

# Casting a tensor to another (tensor) datatype 
 

In [38]:
i = tf.cast(tensor1, dtype= tf.int32)

i 

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

With truncation 


In [39]:
j = tf.cast(tf.constant(4.9), dtype= tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

# Declaring Ragged Tensors

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths. There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array. 

The following example shows how to declare a constant ragged array and the lengths of the individual slices:

In [40]:
ragged = tf.ragged.constant([[3,2,6,1], [], [4,10,7], [8], [6,7]])

print(ragged)

<tf.RaggedTensor [[3, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>


In [41]:
print(ragged[0])

tf.Tensor([3 2 6 1], shape=(4,), dtype=int32)


In [42]:
print(ragged[1])

tf.Tensor([], shape=(0,), dtype=int32)


In [43]:
print(ragged[2])

tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)


In [44]:
print(ragged[3])

tf.Tensor([8], shape=(1,), dtype=int32)


In [45]:
print(ragged[4])

tf.Tensor([6 7], shape=(2,), dtype=int32)


# Finding the square difference between two tensors


In [46]:
varx = [1,3,5,7,11]
vary = 5
varz = tf.math.squared_difference(varx, vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36])>

The python variable, varx and vary are cast into tensors and that vary is then broadcast accross varx  in this example. So, for example the first calculation is (1-5)^2 = 16

# Finding the mean 

The following is the signature of tf.reduce_mean()

Note that this is equavalent to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type (defaulting to float64):

tf.reduce_mean(input_tensor, axis = None, keepdims = None, name = None)

In [47]:
# Definig a constant
num = tf.constant([[4., 5.], [7., 3.]])


In [48]:
# Find the mean accross all axes (use the default axis = None)
tf.reduce_mean(input_tensor=num)

# how calculation take place is (4. + 5. + 7. + 3.)/4

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

In [49]:
# Finding the mean accross columns(that is, reduce rows) with this: 

tf.reduce_mean(input_tensor=num, axis=0)  
# # how calculation take place is [(4.  + 7.)/ 2 , (5. + 3.)/2 ] = [5.5,  4.]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [50]:
# when Keepdins is ture, the reduced axis  is retained with a length of 1:
tf.reduce_mean(input_tensor=num, axis=0, keepdims= True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

Find the mean accross rows (that is, reduce columns) with this:



In [51]:
tf.reduce_mean(input_tensor = num, axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

 When keepdims is True, the reduced axis is retained with a length of 1:
 

In [52]:
tf.reduce_mean(input_tensor= num, axis=1, keepdims= True) 

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

# Generating tensors filled with random values 

# Using tf.random.normal()

tf.random.normal() outputs a tensor of the given shape filled with values of the dtype from a normal distribution. 


The required signature is as follows :


tf.random.normal(shape, mean = 0, stddev = 2, dtype = tf.float32, seed = None, name = None)

In [53]:
tf.random.normal(shape= (3,2), mean = 10, stddev= 2, dtype= tf.float32, seed= None, name= None)
ran = tf.random.normal(shape= (3,2), mean= 10.0,  stddev= 2.0 )
print(ran)

tf.Tensor(
[[10.053534 11.173449]
 [11.905958  9.047728]
 [14.362137  9.961294]], shape=(3, 2), dtype=float32)


Using tf.random.uniform()

The required signature is this: 

tf.random.uniform(shape, minval = 0, maxval = None, dtype = float32, seed = None, name = None)


This outputs a tensor of the given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bond isn't. Take this for example:

In [54]:
tf.random.uniform(shape = (2,4), minval = 0, maxval = None, dtype = tf.float32, seed = None, name = None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.08038533, 0.8024554 , 0.8135786 , 0.6222193 ],
       [0.5593929 , 0.49539304, 0.78305185, 0.27139664]], dtype=float32)>

Setting the seed 

In [55]:
tf.random.set_seed(11)
ran1 = tf.random.uniform(shape = (2,2), maxval= 10, dtype= tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval= 10, dtype= tf.int32)

print(ran1)  # call 1
print(ran2)  

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [56]:
tf.random.set_seed(11)    # same seed
ran1 = tf.random.uniform(shape = (2,2), maxval= 10, dtype= tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval= 10, dtype= tf.int32)

print(ran1)  #call 1
print(ran2)  

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [57]:
tf.random.set_seed(12)
ran1 = tf.random.uniform(shape = (2,2), maxval= 10, dtype= tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval= 10, dtype= tf.int32)

print(ran1)  # call 1
print(ran2)  

tf.Tensor(
[[2 2]
 [6 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[8 2]
 [2 2]], shape=(2, 2), dtype=int32)


# Practical Example of random values using Dices



In [58]:
dice1 = tf.Variable(tf.random.uniform([10,1], minval= 1, maxval= 7, dtype= tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1], minval= 1, maxval= 7, dtype= tf.int32))

# we may add dice 1 and dice2 since they share the same shape and size. 

dice_sum = dice1 + dice2

# we've got three separate 10 x 1 matrices. To produce a single 
# 10 x 3 matrix, we'll concatenate them along dimension 1. 

resulting_matrix = tf.concat(values= [dice1, dice2, dice_sum],  axis = 1)

print(resulting_matrix)

tf.Tensor(
[[ 3  6  9]
 [ 3  3  6]
 [ 4  6 10]
 [ 1  1  2]
 [ 1  6  7]
 [ 4  4  8]
 [ 3  6  9]
 [ 2  2  4]
 [ 2  1  3]
 [ 4  2  6]], shape=(10, 3), dtype=int32)


Finding the indices of the largest and smallest element

The signature of the function are as follow :

tf.argmax(input, axis = None, name = None, output_type = tf.int64)


tf.argmin(input, axis = None, name = None, output_type = tf.int64)

In [59]:
# 1 - D tensor 
t5 = tf.constant([2,11, 5, 42, 7, 19, -6, -11, 29])
print(t5)

i = tf.argmax(input= t5)
print('index of max: ', i)
print('Max element: ', t5[i].numpy())

i = tf.argmin(input= t5, axis= 0).numpy()
print('index of min: ', i)
print('Min element: ', t5[i].numpy())


t6 = tf.reshape(t5, [3,3])
print(t6)

i = tf.argmax(input= t6, axis= 0).numpy()  # max arg down rows
print('indices of max down rows: ', i)

i = tf.argmin(input=t6, axis= 0).numpy()   # min arg down rows
print('indices of min down rows : ', i)
print(t6)


i = tf.argmax(input= t6, axis= 1).numpy()   # max arg across cols
print('indices of max accross cols:', i)


i = tf.argmin(input= t6, axis= 1).numpy()   # max arg across cols
print('indices of min accross cols:', i)

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max:  tf.Tensor(3, shape=(), dtype=int64)
Max element:  42
index of min:  7
Min element:  -11
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows:  [1 0 2]
indices of min down rows :  [2 2 0]
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max accross cols: [1 0 2]
indices of min accross cols: [0 1 1]


# Saving and restoring tensor values using a checkpoint

In [61]:
variable = tf.Variable([[1,3,5,7], [11, 13, 17, 19]])
checkpoint = tf.train.Checkpoint(var = variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0], [0,0,0,0]])
variable
print(variable)
checkpoint.restore(save_path) # gives previous value
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]])>


## Using tf.function


tf.function is a function that will take a Python function and return a Tensorflow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func).  tf.function is new to Tensorflow 2.


Its signature is as follows:

tf.function(func = None, input_signature = None, autograph = True, experimental_autograph_options = None)

In [62]:
def f1(x,y):
    return tf.reduce_mean(input_tensor= tf.multiply(x ** 2, 5) + y ** 2)

f2 = tf.function(f1)
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

#f1 and f2 return the same value, but f2 executes as a Tensorflow graph
assert f1(x,y). numpy() == f2(x,y).numpy()

# The assert passes, so there is no output 

# Calculating the gradient 

In [63]:
# Gradient Tape 

# Another difference from numpy is that it can automatically track the gradient of any variable 

a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.5899688   0.99301827]
 [ 0.39844632 -0.9196171 ]], shape=(2, 2), dtype=float32)


For all variables, the calculation is tracked by default and used to find the gradient, so do not usetape.watch()

In [65]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.5899688   0.99301827]
 [ 0.39844632 -0.9196171 ]], shape=(2, 2), dtype=float32)


we can gradient tapefind higher-order derivatives by opening a few more:


In [67]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a) + tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da, a)
    print(d2c_d2a)

tf.Tensor(
[[0.93744546 0.02618289]
 [0.4112303  0.13079149]], shape=(2, 2), dtype=float32)
