Version check for tensorflow

In [5]:
import tensorflow as tf

print ("Tensorflow version: {}". format(tf.__version__))
print ("Eager execution is: {}". format(tf.executing_eagerly))
print ("Keras version: {}". format(tf.keras.__version__))

Tensorflow version: 2.12.0
Eager execution is: <function executing_eagerly at 0x0000028ABD464EA0>
Keras version: 2.12.0


In [6]:

if tf.config.list_physical_devices('GPU'):
    print("Running on GPU")
else:
    print("Running on CPU")


Running on CPU


Tensor Constant

In [7]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
ineuron.numpy()

42

In [9]:
ineuron1 = tf.constant(1, dtype= tf.int64)
ineuron1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [11]:
# passing 2D array to the constant value
ineuron_x = tf.constant([[4,2], [9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [12]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]])

In [13]:
print('shape:', ineuron_x.shape)
print(ineuron_x.dtype)


shape: (2, 2)
<dtype: 'int32'>


Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones and np.zeros

In [14]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [15]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [18]:
# declaring multiple constants
const2 = tf.constant([[3,4,5], [3,4,5]])
const1 = tf.constant([[1,2,3], [1,2,3]])
result = tf.add(const1,const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


Random Constant

In [19]:
# generating shape using standard normal distribution 
tf.random.normal(shape = (2,2), mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.42954612, -0.32559174],
       [-0.815531  , -0.2305776 ]], dtype=float32)>

In [20]:
tf.random.uniform(shpae = (2,2), minval= 0, maxval= 10, dtype= tf.int32)

TypeError: Got an unexpected keyword argument 'shpae'